"""Auto-generated migration template."""
from alembic import op
import sqlalchemy as sa

revision = "23829ba2e1c3"
down_revision = 'db01a6f8d01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('raw_platform', sa.String(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('library_entry_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('proposed_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['library_entry_id'], ['user_library.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_candidates_id'), 'import_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_import_candidates_status'), 'import_candidates', ['status'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('raw_platform', sa.String(), nullable=False),
    sa.Column('raw_date', sa.String(), nullable=True),
    sa.Column('raw_playthroughs', sa.String(), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('raw_collection', sa.String(), nullable=True),
    sa.Column('source_tab', sa.String(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('playthroughs', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['import_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_id'), 'import_rows', ['id'], unique=False)
    op.add_column('completions', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completions', 'sort_order')
    op.drop_index(op.f('ix_import_rows_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_candidates_status'), table_name='import_candidates')
    op.drop_index(op.f('ix_import_candidates_id'), table_name='import_candidates')
    op.drop_table('import_candidates')
    # ### end Alembic commands ###

