"""Auto-generated migration template."""
from alembic import op
import sqlalchemy as sa

revision = "415b9dcd0449"
down_revision = '6c1a3420f773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_releases', sa.Column('metadata_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_releases', 'metadata_fetched_at')
    # ### end Alembic commands ###

