"""Auto-generated migration template."""
from alembic import op
import sqlalchemy as sa

revision = "6c1a3420f773"
down_revision = 'c46b632bdfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('steam_session_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('steam_login_secure', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'steam_login_secure')
    op.drop_column('users', 'steam_session_id')
    # ### end Alembic commands ###

