"""Drop deprecated artwork override columns from user_library.

cover_url_override_v, cover_url_override_h, hero_url_override, and
logo_url_override were migrated to the user_artwork table in
f1a2b3c4d5e6. All read/write paths now use UserArtwork; these columns
are dead weight. Also fixes user_artwork index names to match the model
(ix_user_artwork_entry_id etc. vs the older short forms)."""
from alembic import op
import sqlalchemy as sa

revision = "a0ad79436a20"
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_artwork_entry'), table_name='user_artwork')
    op.drop_index(op.f('ix_user_artwork_game'), table_name='user_artwork')
    op.drop_index(op.f('ix_user_artwork_user'), table_name='user_artwork')
    op.create_index(op.f('ix_user_artwork_entry_id'), 'user_artwork', ['entry_id'], unique=False)
    op.create_index(op.f('ix_user_artwork_game_id'), 'user_artwork', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_artwork_id'), 'user_artwork', ['id'], unique=False)
    op.create_index(op.f('ix_user_artwork_user_id'), 'user_artwork', ['user_id'], unique=False)
    op.drop_column('user_library', 'hero_url_override')
    op.drop_column('user_library', 'logo_url_override')
    op.drop_column('user_library', 'cover_url_override_h')
    op.drop_column('user_library', 'cover_url_override_v')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_library', sa.Column('cover_url_override_v', sa.VARCHAR(), nullable=True))
    op.add_column('user_library', sa.Column('cover_url_override_h', sa.VARCHAR(), nullable=True))
    op.add_column('user_library', sa.Column('logo_url_override', sa.VARCHAR(), nullable=True))
    op.add_column('user_library', sa.Column('hero_url_override', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_user_artwork_user_id'), table_name='user_artwork')
    op.drop_index(op.f('ix_user_artwork_id'), table_name='user_artwork')
    op.drop_index(op.f('ix_user_artwork_game_id'), table_name='user_artwork')
    op.drop_index(op.f('ix_user_artwork_entry_id'), table_name='user_artwork')
    op.create_index(op.f('ix_user_artwork_user'), 'user_artwork', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_artwork_game'), 'user_artwork', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_artwork_entry'), 'user_artwork', ['entry_id'], unique=False)
    # ### end Alembic commands ###

