"""Auto-generated migration template."""
from alembic import op
import sqlalchemy as sa

revision = "c46b632bdfd1"
down_revision = '0cc6c1137008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('steam_last_dlc_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'steam_last_dlc_synced_at')
    # ### end Alembic commands ###

