"""Auto-generated migration template."""
from alembic import op
import sqlalchemy as sa

revision = "cf19768819ef"
down_revision = 'd06055a76713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_releases_external_id'), 'game_releases', ['external_id'], unique=False)
    op.create_index(op.f('ix_game_releases_source'), 'game_releases', ['source'], unique=False)
    op.create_index(op.f('ix_games_title'), 'games', ['title'], unique=False)
    op.create_index(op.f('ix_user_library_release_id'), 'user_library', ['release_id'], unique=False)
    op.create_index(op.f('ix_user_library_user_id'), 'user_library', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_library_user_id'), table_name='user_library')
    op.drop_index(op.f('ix_user_library_release_id'), table_name='user_library')
    op.drop_index(op.f('ix_games_title'), table_name='games')
    op.drop_index(op.f('ix_game_releases_source'), table_name='game_releases')
    op.drop_index(op.f('ix_game_releases_external_id'), table_name='game_releases')
    # ### end Alembic commands ###

