"""Auto-generated migration template."""
from alembic import op
import sqlalchemy as sa

revision = "cfccdfb8c419"
down_revision = '0a08baf534e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completions_id'), ['id'], unique=False)

    with op.batch_alter_table('game_artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_artwork_id'), ['id'], unique=False)

    with op.batch_alter_table('game_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_releases_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_releases_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_releases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_releases_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_releases_source'), ['source'], unique=False)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_is_collection'), ['is_collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_is_dlc'), ['is_dlc'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_title'), ['title'], unique=False)

    with op.batch_alter_table('import_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_import_candidates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_candidates_status'), ['status'], unique=False)

    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_id'), ['id'], unique=False)

    with op.batch_alter_table('platform_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_aliases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_aliases_platform_id'), ['platform_id'], unique=False)

    with op.batch_alter_table('platform_families', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_families_id'), ['id'], unique=False)

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_id'), ['id'], unique=False)

    with op.batch_alter_table('sync_match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_match_candidates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_match_candidates_manual_entry_id'), ['manual_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_match_candidates_status'), ['status'], unique=False)

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_id'), ['id'], unique=False)

    with op.batch_alter_table('user_artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_artwork_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_artwork_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_artwork_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_artwork_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_library_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_library_import_source'), ['import_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_library_is_hidden'), ['is_hidden'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_library_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_library_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_token'), ['api_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_api_token'))

    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_library_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_library_release_id'))
        batch_op.drop_index(batch_op.f('ix_user_library_is_hidden'))
        batch_op.drop_index(batch_op.f('ix_user_library_import_source'))
        batch_op.drop_index(batch_op.f('ix_user_library_id'))

    with op.batch_alter_table('user_artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_artwork_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_artwork_id'))
        batch_op.drop_index(batch_op.f('ix_user_artwork_game_id'))
        batch_op.drop_index(batch_op.f('ix_user_artwork_entry_id'))

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_id'))

    with op.batch_alter_table('sync_match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_match_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_sync_match_candidates_manual_entry_id'))
        batch_op.drop_index(batch_op.f('ix_sync_match_candidates_id'))

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_id'))

    with op.batch_alter_table('platform_families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_families_id'))

    with op.batch_alter_table('platform_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_aliases_platform_id'))
        batch_op.drop_index(batch_op.f('ix_platform_aliases_id'))

    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_id'))

    with op.batch_alter_table('import_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_import_candidates_id'))
        batch_op.drop_column('thumbnail_url')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_title'))
        batch_op.drop_index(batch_op.f('ix_games_parent_id'))
        batch_op.drop_index(batch_op.f('ix_games_is_dlc'))
        batch_op.drop_index(batch_op.f('ix_games_is_collection'))
        batch_op.drop_index(batch_op.f('ix_games_id'))

    with op.batch_alter_table('game_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_releases_source'))
        batch_op.drop_index(batch_op.f('ix_game_releases_platform_id'))
        batch_op.drop_index(batch_op.f('ix_game_releases_id'))
        batch_op.drop_index(batch_op.f('ix_game_releases_game_id'))
        batch_op.drop_index(batch_op.f('ix_game_releases_external_id'))

    with op.batch_alter_table('game_artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_artwork_id'))

    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completions_id'))

    # ### end Alembic commands ###

