"""Auto-generated migration template."""
from alembic import op
import sqlalchemy as sa

revision = "d06055a76713"
down_revision = '2c9028a8f2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('steam_id64', sa.String(), nullable=True))
    op.add_column('users', sa.Column('steam_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('steam_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'steam_last_synced_at')
    op.drop_column('users', 'steam_api_key')
    op.drop_column('users', 'steam_id64')
    # ### end Alembic commands ###

